#!/usr/bin/env python3
"""Authorized shared-profile calibration driver for TASK-007."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path

from isaaclab.app import AppLauncher

from common import generate_manifest, run_live_trial, summarize_trials, write_json


ROOT = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--scene", choices=("flat",), default="flat")
parser.add_argument("--trials-per-action", type=int, default=3)
parser.add_argument("--search-budget", type=int, default=20)
parser.add_argument("--seed", type=int, default=17007)
parser.add_argument("--output", type=Path, default=ROOT / "logs/virtual_magnet/calibration/latest.json")
AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()
args_cli.enable_cameras = False
launcher = AppLauncher(args_cli)
simulation_app = launcher.app

import gymnasium as gym
import robotarm_magnetic_lab.tasks  # noqa: F401,E402
from isaaclab.app import launch_simulation
from isaaclab_tasks.utils import parse_env_cfg


def main() -> None:
    # The executable evaluates the checked-in profile first. Additional
    # candidates are only generated by explicit profile edits so every tuned
    # value remains reviewable and versioned; it never mutates physics.
    specs = generate_manifest("development-calibration", args_cli.trials_per_action, base_seed=args_cli.seed)
    cfg = parse_env_cfg("Template-Robotarm-Magnetic-Virtual-Magnet-Flat-Lab-v0", device=args_cli.device, num_envs=1)
    cfg.scene.capsule_camera = None
    rows = []
    with launch_simulation(cfg, args_cli):
        env = gym.make("Template-Robotarm-Magnetic-Virtual-Magnet-Flat-Lab-v0", cfg=cfg)
        for spec in specs:
            rows.append(run_live_trial(env, spec))
        env.close()
    summary = summarize_trials(rows)
    payload = {
        "schema_version": "task007_calibration_v1",
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "search_budget_max": args_cli.search_budget,
        "evaluated_candidates": 1,
        "selection": "checked-in shared profile",
        "aggregate": summary,
        "rows": rows,
    }
    write_json(args_cli.output, payload)
    print("VIRTUAL_MAGNET_CALIBRATION " + json.dumps(summary, sort_keys=True), flush=True)


if __name__ == "__main__":
    try:
        main()
    finally:
        simulation_app.close()

